os: linux

language: java

jdk:
 - openjdk8

install: true

script:
  mvn
    --file mq
    --no-transfer-progress
    --show-version
    --batch-mode
    --activate-profiles staging
    clean install &&
  mvn --file mq/distribution
    --no-transfer-progress
    --batch-mode
    --activate-profiles staging
    source:jar install
