github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Eclipse OpenMQ]
description: [Eclipse Open Message Queue (Eclipse Open MQ) -- A complete JMS MOM Platform]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/openmq
  download: https://projects.eclipse.org/projects/ee4j.glassfish/downloads
  mailinglist: https://accounts.eclipse.org/mailing-list/openmq-dev
  #javadocs:
  docs: https://eclipse-ee4j.github.io/openmq/guides/
  #faq:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

include:
  LICENSE.md
  CONTRIBUTING.md
