#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

on:
  workflow_call:
    inputs:
      java_distribution:
        required: false
        type: string
        default: 'zulu'
      java_version:
        required: true
        type: string
      mq_distribution_artifact:
        required: false
        type: string
        default: 'mq-distribution'

jobs:
  build:
    name: Test on JDK ${{ inputs.java_version }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout for build
      uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
    - name: Test Maven Build
      run: ./mvnw --show-version --no-transfer-progress --file mq/main install --define build.letter=g --define build.number=${GITHUB_REF_NAME}/${GITHUB_SHA}/${GITHUB_RUN_ID}.${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT} --define skipSBOM
    - name: Upload MQ Distribution
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.mq_distribution_artifact }}
        retention-days: 1
        path: mq/dist/bundles/mq.zip
